# Generated by Django 5.0.2 on 2024-02-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locales", "0002_alter_local_options_category_gallery_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="image",
            field=models.ImageField(
                default=1,
                upload_to="local_gallery_image/",
                verbose_name="Imagen del local",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="local",
            name="image",
            field=models.ImageField(
                null=True, upload_to="locals", verbose_name="Imagen"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="product_image/", verbose_name="Imagen"
            ),
        ),
    ]
