# Generated by Django 5.0.2 on 2024-02-28 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locales", "0004_product_discription_alter_category_local_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="local",
            name="visit",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Visitado"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="visit",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Visitado"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="local",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categoryLocal",
                to="locales.local",
                verbose_name="Local",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="local",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="galleryLocal",
                to="locales.local",
                verbose_name="Local",
            ),
        ),
    ]
