# Generated by Django 5.0.2 on 2024-03-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locales", "0006_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="local",
            name="description",
            field=models.TextField(
                default="Descricción del Local", verbose_name="Descricción del Local"
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(
                upload_to="local_gallery_image/",
                verbose_name="Dimenciones de imagen:(640x540)",
            ),
        ),
        migrations.AlterField(
            model_name="local",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to="locals",
                verbose_name="Dimenciones de imagen:(752x450)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product_image/",
                verbose_name="Dimenciones de imagen:(752x450)",
            ),
        ),
    ]
