# Generated by Django 5.0.2 on 2024-03-03 21:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locales", "0007_local_description_alter_gallery_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discription",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stars",
        ),
        migrations.RemoveField(
            model_name="product",
            name="visit",
        ),
    ]
