# Generated by Django 5.0.2 on 2024-03-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locales", "0008_remove_product_discription_remove_product_stars_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="measurement_unit",
            field=models.CharField(
                default="unidades", max_length=50, verbose_name="Unidad de medida"
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="measurement_unit_quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=4,
                max_digits=10,
                verbose_name="cantidad en unidades de medida",
            ),
        ),
    ]
