# Generated by Django 5.0.2 on 2024-03-04 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locales", "0009_ingredient_measurement_unit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(max_length=50, verbose_name="Nombre del usuario"),
                ),
                (
                    "description",
                    models.TextField(
                        default="Me encanta el servicio que brindan",
                        verbose_name="Reseña",
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locales.local",
                        verbose_name="Local",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reseña",
                "verbose_name_plural": "Reseñas",
            },
        ),
    ]
