# Generated by Django 5.0.2 on 2024-03-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locales", "0010_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
