# Generated by Django 5.0.2 on 2024-03-04 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locales", "0011_reviews_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="time",
            field=models.DateTimeField(auto_now=True, verbose_name="Tiempo"),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="local",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewsLocal",
                to="locales.local",
                verbose_name="Local",
            ),
        ),
    ]
