# Generated by Django 5.0.2 on 2024-03-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locales", "0012_favorite_time_alter_reviews_local"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="date",
            field=models.DateField(auto_now_add=True, null=True, verbose_name="Fecha"),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="time",
            field=models.TimeField(auto_now_add=True, null=True, verbose_name="Hora"),
        ),
    ]
