# Generated by Django 5.0.2 on 2024-03-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locales", "0013_favorite_date_alter_favorite_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="local",
            name="facebook",
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="local",
            name="instagram",
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="local",
            name="telegram",
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="local",
            name="twitter",
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="local",
            name="whatsapp",
            field=models.URLField(max_length=500, null=True),
        ),
    ]
