# Generated by Django 5.0.2 on 2024-03-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locales", "0014_local_facebook_local_instagram_local_telegram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="local",
            name="facebook",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="local",
            name="instagram",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="local",
            name="telegram",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="local",
            name="twitter",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="local",
            name="whatsapp",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
