# Generated by Django 5.0.2 on 2024-03-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locales", "0015_alter_local_facebook_alter_local_instagram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(
                upload_to="local_gallery_image",
                verbose_name="Dimenciones de imagen:(640x540)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product_image",
                verbose_name="Dimenciones de imagen:(752x450)",
            ),
        ),
    ]
