# Generated by Django 5.0.2 on 2024-03-03 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locales", "0005_local_visit_product_visit_alter_category_local_and_more"),
        ("ofertas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promo",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="promo",
            name="local",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promoLocal",
                to="locales.local",
            ),
        ),
    ]
