# Generated by Django 5.0.2 on 2024-03-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ofertas", "0002_promo_active_alter_promo_local"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="image_three",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="image_two",
        ),
        migrations.AlterField(
            model_name="offer",
            name="image_first",
            field=models.ImageField(
                blank=True, null=True, upload_to="offer_image/", verbose_name="Imagen"
            ),
        ),
    ]
