# Generated by Django 5.0.2 on 2024-03-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ofertas", "0003_remove_offer_image_three_remove_offer_image_two_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="image_first",
            field=models.ImageField(
                blank=True, null=True, upload_to="offer_image", verbose_name="Imagen"
            ),
        ),
    ]
