# Generated by Django 5.0.2 on 2024-03-04 14:17

import django.core.validators
import django.db.models.deletion
import utils.validates.validates
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locales", "0014_local_facebook_local_instagram_local_telegram_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Costo"
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookingLocal",
                        to="locales.local",
                        verbose_name="Local",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Nombre del usuario"),
                ),
                (
                    "cant",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cantidad de personas",
                    ),
                ),
                (
                    "ci",
                    models.CharField(
                        max_length=11,
                        validators=[
                            django.core.validators.MinLengthValidator(11),
                            utils.validates.validates.validate_digits,
                        ],
                        verbose_name="Carnet",
                    ),
                ),
                (
                    "movil",
                    models.CharField(
                        max_length=8,
                        validators=[
                            django.core.validators.MinLengthValidator(8),
                            utils.validates.validates.validate_digits,
                        ],
                        verbose_name="Movil",
                    ),
                ),
                ("booking_date", models.DateField(verbose_name="Fecha")),
                ("booking_time", models.TimeField(verbose_name="Hora")),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservas.booking",
                        verbose_name="Reserva",
                    ),
                ),
            ],
        ),
    ]
