# Generated by Django 5.0.2 on 2024-03-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
    ]
