# Generated by Django 5.0.2 on 2024-03-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservas", "0003_alter_booking_options_alter_clientbooking_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Receservaciones",
            },
        ),
        migrations.AddField(
            model_name="clientbooking",
            name="booking_active",
            field=models.BooleanField(default=False, verbose_name="Reservado"),
        ),
    ]
