# Generated by Django 5.0.2 on 2024-03-05 01:40

import django.core.validators
import utils.validates.validates
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservas", "0004_alter_booking_options_clientbooking_booking_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cant",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Máximo de personas"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="name",
            field=models.CharField(
                default="Reserva",
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    utils.validates.validates.validate_letters_numbers_and_spaces,
                ],
                verbose_name="Nombre de la reserva",
            ),
        ),
        migrations.AlterField(
            model_name="clientbooking",
            name="name",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    utils.validates.validates.validate_letters_and_spaces,
                ],
                verbose_name="Nombre del usuario",
            ),
        ),
    ]
