# Generated by Django 5.0.2 on 2024-02-24 17:01

import django.core.validators
import utils.validates.validates
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    utils.validates.validates.validate_letters_and_spaces,
                ],
                verbose_name="Nombre",
            ),
        ),
    ]
