# Generated by Django 5.0.2 on 2024-02-24 17:31

import apps.usuarios.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_remove_user_name_alter_user_first_name"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.usuarios.models.UserManager()),
            ],
        ),
    ]
